---
 model:
   model_type: DINO
   arch: vit_tiny
   root: /
   data_path: exploratory_configs/1d_hpa_fov.csv
   output_dir: results_01_11_from_features_1channel_dino
   datatype: HPA
   image_mode: normalized_4_channels # set to this to use the default_loader
   saveckp_freq: 50
   batch_size_per_gpu: 64
   num_channels: 1
   patch_size: 16
   epochs: 50
   momentum_teacher: 0.996
   center_momentum: 0.9
   sample_single_cells: False
   lr: 0.0005
   local_crops_scale: '0.2 0.5'

 embedding:
   pretrained_weights: output_12-10_1d/checkpoint.pth
   output_path: results_01_09_from_features_1channel_dino_kaggle_train_data.pth
   # Or results_01_09_from_features_1channel_dino
   df_path: exploratory_configs/kaggle_1channel_train_data.csv
   # kaggle_1channel_test_data.csv for generating features from kaggle test data
   # exploratory_configs/filtered_updated_whole_images.csv for training classifier
   # 1d_hpa_fov.csv for generating features from hpa training 1d data
   image_size: 224
   num_workers:  1
   embedding_has_labels: False # setting to false so that it can load id, file.
   target_labels: [nucleoplasm,nuclear membrane,nucleoli,nucleoli fibrillar center,nuclear speckles,nuclear bodies,endoplasmic reticulum,golgi apparatus,peroxisomes,endosomes,lysosomes,intermediate filaments,actin filaments,focal adhesion sites,microtubules,microtubule ends,cytokinetic bridge,mitotic spindle,microtubule organizing center,centrosome,lipid droplets,plasma membrane,cell junctions,mitochondria,aggresome,cytosol,cytoplasmic bodies,rods & rings]
