name: dinov1
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - cudatoolkit=11.6
  - imageio=2.19.3
  - kornia=0.6.8
  - numpy=1.23.5
  - oyaml=1.0
  - pandas=1.5.3
  - pillow=9.5.0
  - pyyaml=6.0
  - scikit-image=0.19.3
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - tqdm=4.64.1
  - pip
  - pip:
    - torch==1.12.1+cu116
    - torchvision==0.13.1+cu116
    - torchaudio==0.12.1
    - --extra-index-url https://download.pytorch.org/whl/cu116
